### ISSUE TITLE
`mkdirp` - replace with native implementation

### ISSUE THREAD

**Issue by wojtekmaj** [es-tooling/module-replacements#104]
In Node.js v10.12.0, `recursive` option was added to [`fs.mkdirSync`](https://nodejs.org/api/fs.html#fsmkdirsyncpath-options). This option allows you to create a directory and all its parent directories if they do not exist.

**Comment by bluwy** [comment]
Isn’t this already covered in https://github.com/es-tooling/module-replacements/pull/41
