### ISSUE TITLE
`rimraf` - replace with native implementation 

### ISSUE THREAD

**Issue by wojtekmaj** [es-tooling/module-replacements#105]
In Node.js v14.14.0, [`fs.rmSync`](https://nodejs.org/api/fs.html#fsrmsyncpath-options) was added. It's a built-in module that removes files and directories. The `recursive` option is used to remove directories and their contents.

**Comment by 43081j** [comment]
There's still a small gap: cli usage

So I think this would go in the preferred manifest and we would document alternatives (passing an inline script to node isn't nice DX)

Also feel like I've seen this already discussed but could be wrong

**Comment by wojtekmaj** [comment]
Codemods give us the flexibility and allow removing programmatic uses only.

**Comment by bluwy** [comment]
Isn’t this already covered in https://github.com/es-tooling/module-replacements/pull/41
