### ISSUE TITLE
Possible Edge Case for `is-plain-object` Replacement Suggestion

### ISSUE THREAD

**Issue by babs20** [es-tooling/module-replacements#108]
**Edge Case:** 
With the current replacement suggestion for `is-plain-object`, if we were to use `Object.create(null)` as `v`, it would incorrectly return `false`.
```js
console.log(
  typeof Object.create(null) === "object" && 
  Object.create(null) !== null && 
  Object.create(null).constructor === Object
 );
 //=> false - incorrect
```

I think we need to add a check to see if the constructor is `undefined` to cover this edge case.
```js
console.log(
  typeof Object.create(null) === "object" && 
  Object.create(null) !== null && 
  (Object.create(null).constructor === Object || Object.create(null).constructor === undefined)
 );
 //=> true - correct
```

**Place of Concern:**
https://github.com/es-tooling/module-replacements/blob/6200ffe0684c7626da0814fb4f624e7cc9fdd1a6/manifests/micro-utilities.json#L60

**Comment by ljharb** [comment]
I don't think that's sufficient. I think you want `obj && typeof obj === 'object' && Object.getPrototypeOf(obj) === null || Object.getPrototypeOf(obj) === Object.prototype`. altho that won't work cross-realm, it's far more reliable than the `constructor` property, which shouldn't ever be relied upon.

**Comment by 43081j** [comment]
i'm not concerned with cross realm since that's the kind of edge case where a third party dependency probably makes sense (or just a little more code)

so I think you're right, we should just check that the prototype is nullish or is the object prototype (via `getPrototypeOf` if that works well)

would be open to contribs for this
