### ISSUE TITLE
`md5` Package

### ISSUE THREAD

**Issue by filipre** [es-tooling/module-replacements#113]
Coming from https://github.com/es-tooling/module-replacements-codemods/pull/30, instead of using the `md5` package, one can use the native `crypto` package in node instead

```javascript
const crypto = require('crypto')
crypto.createHash('md5').update('hello world').digest('hex')
```

However, this does not work in the browser. Should we add it? How should we document that this only works in node?

**Comment by 43081j** [comment]
We should probably recommend web crypto but it won't support md5 since it isn't secure

Not too sure of the best thing to do here. Open to suggestions

**Comment by filipre** [comment]
Option 1: We leave it as it is
- `+` we are fine with people continuing using the package if there isn't a simple alternative for md5
- `-` currently it's being used 7 million times per week, so I do see a potential to replace it

Option 2: We discourage md5 in general
- `+` we raise awareness not to use it anymore
- `+` consistent advice across all platforms
- `-` no immediate fix for the user and often its difficult to change algorithms

Option 3: We recommend `crypto` for node only but still discourage `md5` and refer to web crypto
- `+` best of both worlds? 
- `-` web users still might use the md5 package in the end

I like option 3 the most but not sure if the current format supports it. Otherwise option 2 seems good as well even if there isn't a fix except replacing it. In some places that should be possible anyway.

**Comment by 43081j** [comment]
the current manifest structure means we'd have to suggest it for all runtimes, not only node

we could possibly add it to the `preferred` manifest and give two alternatives:

1. use web crypto and drop md5
2. use `crypto` in node environments

**Comment by filipre** [comment]
I was going to close this since `md5` has been added to the manifests [here](https://github.com/es-tooling/module-replacements/commit/7c2b3bbcde60e0eab167ab7592d9d4d10b9b109d#diff-c315ae72564f9dbc1bd960118667113e5dc24a3e1867153537712515ada3d24aR2079) but its gone again due to [this](https://github.com/es-tooling/module-replacements/commit/3faadca06fc3ca24c88a747e8fdf3ef53eb5342d#diff-c315ae72564f9dbc1bd960118667113e5dc24a3e1867153537712515ada3d24aL2080) commit. What was the reason?

**Comment by 43081j** [comment]
as you can see, that commit was sorting the modules, so was certainly unintentional that it removed `md5`

i will add it back. somewhere down the line there must've been some bad git fu
