### ISSUE TITLE
Analyze peerDependencies in DepTree

### ISSUE THREAD

**Issue by rajsite** [es-tooling/module-replacements#121]
Doesn't look like DepTree detects peerDependencies in a package. For example: 
![Screenshot_20240727-172728](https://github.com/user-attachments/assets/7d3c7bbd-d104-4cf9-a7fe-cf98d8328f95)

![Screenshot_20240727-172824](https://github.com/user-attachments/assets/56ea72a2-420d-4189-ae4b-59511a73607b)

**Comment by 43081j** [comment]
this probably belongs in the deptree repo assuming there is one

maybe ping @rschristian to decide where to open issues like this.

will close this meanwhile

**Comment by rschristian** [comment]
Deptree repo is at https://github.com/rschristian/deptree, the GitHub icon at the top of the webpage will take you there.

As for the issue, I've gone back and forth on it. Feel free to open a new issue but I'm not yet decided if I want to show peer deps or not for packages.
