### ISSUE TITLE
jQuery alternatives

### ISSUE THREAD

**Issue by Lehoczky** [es-tooling/module-replacements#13]
The exact alternatives could be:

- native JS
- some more robust frameworks, like Angular, React, Vue
- some lighter alternatives, like [htmx ](https://htmx.org/)or [Alpine.js](https://alpinejs.dev/)

**Comment by 43081j** [comment]
with how big jquery is (the amount of areas it covers), maybe we should just suggest using native functionality?

a quick search across github found this for example:
https://github.com/prometheus/prometheus/blob/114dc5c393ce54ac663a2466a82571e1e0e0d03d/web/ui/react-app/src/pages/graph/Graph.tsx#L111

which, presumably, they could just do with `querySelector`

remember, people will be using it for fetch-like functionality too and other util-like things
