### ISSUE TITLE
dotenv

### ISSUE THREAD

**Issue by Jayllyz** [es-tooling/module-replacements#152]
Suggest dotenvx instead

**Comment by Mouvedia** [comment]
You mean [`dotenvx`](https://dotenvx.com).

**Comment by jonasb** [comment]
What about Node's built-in `--env-file` https://nodejs.org/dist/latest-v20.x/docs/api/cli.html#--env-fileconfig? I prefer it since it's one less dependency, at least for simple use cases. (tsx, bun and deno also support `--env-file`)

**Comment by 43081j** [comment]
Good find! Had no idea node has this built in now

If we don't already, we should mention it in the replacements repo for dotenv
