### ISSUE TITLE
replace: `path-exists` -> native

### ISSUE THREAD

**Issue by lukeed** [es-tooling/module-replacements#156]
The [path-exists](https://www.npmjs.com/package/path-exists?activeTab=readme) module gets 82M/week and its readme admits it's pointless in a post-Node 6.x world

```js
import { existsSync } from 'node:fs';
import { access } from 'node:fs/promises';

export { existsSync as pathExistsSync }

export function pathExists(s) {
  return access(s).then(() => true).catch(() => false);
}
```

**Comment by 43081j** [comment]
I think we can close this thanks to #157 

I don't think we need to document an async case necessarily. If it turns out people need async, hopefully an issue will be opened
