### ISSUE TITLE
Replace `fast-glob` with `tinyglobby` in stylelint

### ISSUE THREAD

**Issue by Namchee** [es-tooling/module-replacements#163]
## Overview

`stylelint` uses it for globbing and `escapePath`. Need to wait for new `tinyglobby`

**Comment by SuperchupuDev** [comment]
FYI the new `tinyglobby` version is out 🎉

**Comment by Mouvedia** [comment]
es-tooling/ecosystem-cleanup#103

**Comment by Namchee** [comment]
Whoops, wrong repository
