### ISSUE TITLE
A "system" to track when packages aren't needed any more

### ISSUE THREAD

**Issue by romainmenke** [es-tooling/module-replacements#166]
At some point in the past `stripVTControlCharacters` was added to node.
This was quasi useless at the time because most packages can't immediately adopt this.
But when something can't be used people forget about it.

However at some point it was supported in all LTS versions of node and it could have been quickly adopted.

In other words `https://www.npmjs.com/package/strip-ansi` should have been dead already.
Instead its usage is only going up more and more.

I think it could be helpful to have a list of features that are adopted as native JavaScript or native to node and when there is broad consensus that these are safe to use.

-----

"Supported in all LTS versions" corresponds roughly with 2.5 - 3 years.
This also aligns with Baseline for the web.

Starting a "timer" each time a native alternative is shipped to then replace it when the timer ends could be a nice way to continually improve the ecosystem.

In it's most basic form this would be a list of features, when the features shipped in some native form and the corresponding npm packages that are made obsolete.

**Comment by romainmenke** [comment]
NVM 😅 

I see that the version of shipping is already present in the manifests: https://github.com/es-tooling/module-replacements/blob/f3086e52a15a713eb7e3c9544ecc495f0d1f8d4a/manifests/native.json#L1046

**Comment by 43081j** [comment]
It is, but maybe we could create a tool some day to automatically detect when a node function makes it into all LTS versions

We could then lookup any packages doing the same and start to move away from them

Just a thought 👀
