### ISSUE TITLE
Suggestions for packages that are now maintained under a different name

### ISSUE THREAD

**Issue by phillip-le** [es-tooling/module-replacements#167]
Sometimes, we have packages which were originally published under one package name but have since moved to another package name for various reasons e.g.

- [faker](https://www.npmjs.com/package/faker) => [@faker-js/faker](https://www.npmjs.com/package/@faker-js/faker)
- [xmldom](https://www.npmjs.com/package/xmldom) => [@xmldom/xmldom](https://www.npmjs.com/package/@xmldom/xmldom)
>Since version 0.7.0 this package is published to npm as [@xmldom/xmldom](https://www.npmjs.com/package/@xmldom/xmldom) and no longer as [xmldom](https://www.npmjs.com/package/xmldom), because [we are no longer able to publish xmldom](https://github.com/xmldom/xmldom/issues/271).
- [eslint-plugin-vitest](https://www.npmjs.com/package/eslint-plugin-vitest) => [@vitest/eslint-plugin](https://www.npmjs.com/package/@vitest/eslint-plugin) (See https://github.com/vitest-dev/eslint-plugin-vitest/issues/537)

Usually in these cases, the NPM package page cannot be updated by the current maintainers so it's not always easy for people coming across the package to realise that the package is currently maintained under a different name. I also think about the case where we have a project that hasn't been maintained in a while and so it's not obvious that to upgrade the packages to the latest version, you need to look for the package under a different name.

Would this be a suitable place to add these suggestions so that it can linted with [eslint-plugin-depend](https://github.com/es-tooling/eslint-plugin-depend/blob/main/src/rules/ban-dependencies.ts)?

**Comment by 43081j** [comment]
I think it makes sense to add them here (and therefore to the eslint plugin) 👍 

the question is if we add them to the preferred manifest or we make a new one. maybe they are fine to go in the existing preferred manifest since its basically an opinionated list of "we prefer package A over package B"

**Comment by phillip-le** [comment]
Yeah that was something I was wondering as well. I’ll raise a PR to add it to the existing preferred manifest 🙇
