### ISSUE TITLE
Chalk alternatives

### ISSUE THREAD

**Issue by Lehoczky** [es-tooling/module-replacements#17]
There are a number of alternatives to [chalk](https://github.com/chalk/chalk) which all tries to be a leaner, more performant alternative:
- [picocolors](https://github.com/alexeyraspopov/picocolors#readme)
- [yoctocolors](https://github.com/sindresorhus/yoctocolors)
- [colorette](https://github.com/jorgebucaran/colorette)

**Comment by Lehoczky** [comment]
We could also want about [colors.js](https://github.com/Marak/colors.js), since it is unmaintained, and had a "regression" in their last releases: https://github.com/Marak/colors.js/issues/285

**Comment by 43081j** [comment]
chalk is an interesting one - since 5.x they have no runtime dependencies, so it isn't anywhere near as bad as it used to be

i think we should document the alternatives here but not necessarily pull it into the linter yet.

especially since chalk 5 is 44KB/5KB (install size / minified size), while picocolors is 5.2KB/1.7KB

its also worth mentioning the latest node includes `styleText` which can be used in common/basic use cases at least (assuming you can require such a node version):
https://nodejs.org/docs/latest/api/util.html#utilstyletextformat-text

**Comment by zloirock** [comment]
I think that the current version of `chalk` is fine and it's not required. Yes, it's not a tiny package, but it's not a reason to recommend replacement.

**Comment by 43081j** [comment]
im going to close this for now at least since chalk is no longer bloated so much 👍

**Comment by webdiscus** [comment]
@Lehoczky,

here is the compare of most popular chalk alternatives: [chalk](https://github.com/chalk/chalk), [ansis](https://github.com/webdiscus/ansis), [kleur](https://github.com/lukeed/kleur), [ansi-colors](https://github.com/doowb/ansi-colors), [kolorist](https://github.com/marvinhagemeister/kolorist), [colorette](https://github.com/jorgebucaran/colorette), [picocolors](https://github.com/alexeyraspopov/picocolors), [cli-color](https://github.com/medikoo/cli-color), [colors-cli](https://github.com/jaywcjlove/colors-cli), [colors.js](https://github.com/Marak/colors.js)

-  [compare by size](https://github.com/webdiscus/ansis#compare-the-size-of-most-popular-packages)
-  [compare features](https://github.com/es-tooling/module-replacements/issues/17?ysclid=m2sv7xk4c94434530#compare)
-  [benchmarks](https://github.com/es-tooling/module-replacements/issues/17?ysclid=m2sv7xk4c94434530#benchmark)

**Comment by dei8bit** [comment]
> @Lehoczky,
> 
> here is the compare of most popular chalk alternatives: [chalk](https://github.com/chalk/chalk), [ansis](https://github.com/webdiscus/ansis), [kleur](https://github.com/lukeed/kleur), [ansi-colors](https://github.com/doowb/ansi-colors), [kolorist](https://github.com/marvinhagemeister/kolorist), [colorette](https://github.com/jorgebucaran/colorette), [picocolors](https://github.com/alexeyraspopov/picocolors), [cli-color](https://github.com/medikoo/cli-color), [colors-cli](https://github.com/jaywcjlove/colors-cli), [colors.js](https://github.com/Marak/colors.js)
> 
> * [compare by size](https://github.com/webdiscus/ansis#compare-the-size-of-most-popular-packages)
> * [compare features](https://github.com/es-tooling/module-replacements/issues/17?ysclid=m2sv7xk4c94434530#compare)
> * [benchmarks](https://github.com/es-tooling/module-replacements/issues/17?ysclid=m2sv7xk4c94434530#benchmark)

I **absolutely love** the sincerity of that readme, this is definitely how all the benchmarks in the dev world should be done.
