### ISSUE TITLE
Suggest replacing cpx with maintenance fork

### ISSUE THREAD

**Issue by wrslatz** [es-tooling/module-replacements#18]
Similar to https://github.com/es-tooling/module-replacements/pull/2, suggest replacing [`cpx`](https://www.npmjs.com/package/cpx) with the [`cpx2` maintenance fork](https://www.npmjs.com/package/cpx2). See https://github.com/renovatebot/renovate/pull/27507 as an example where I contributed something similar to another tool. I'm happy to contribute this here as well.

**Comment by 43081j** [comment]
good catch! makes sense to me

would you be up for opening a PR? there's a template you can follow [here](https://github.com/es-tooling/module-replacements/blob/main/docs/templates/module.md)

you can ignore the manifests for now until we sort the automation out around that

**Comment by wrslatz** [comment]
Opened https://github.com/es-tooling/module-replacements/pull/19 and https://github.com/es-tooling/eslint-plugin-depend/pull/17 for this one 🙏🏻 Didn't look like any tests needed updating. Happy to make any changes, if needed.
