### ISSUE TITLE
Selection criteria

### ISSUE THREAD

**Issue by will-stone** [es-tooling/module-replacements#189]
Hi. This is a great project! Thank you ☺️ 

What’s the current selection criteria for replacements? 

I’m wondering if it may be a little dangerous to recommend swaps, that people _will_ blindly make, without a package fulfilling a few requirements first. 

For example, lint-staged is very much actively maintained, whereas nano-staged’s last publish was 3 years ago and is still on 0.x releases. Not that it’s not a great project but I’d be wary to recommend it to colleagues, over lint-staged, based on those stats.

I’ve not been through any other recommendations yet. 

Thanks again,

Will.

**Comment by 43081j** [comment]
The replacements are generally thoroughly discussed either on here (github) or in our discord

We don't have a list of criteria a package has to fit to join the list, as I think that would be too restrictive and wouldn't allow for newer packages to be recommended. 

A few examples of what we might look for:

- actively maintained (this doesn't mean the last publish has to be recent. stability is good, its often a good sign if something hasn't changed in a while. you're better looking at the maintainers and seeing that they're actively watching and maintaining it)
- package being replaced is unlikely to accept the changes we'd want (sometimes its too big of a refactor. but if this is not the case, we should contribute upstream instead)
- maintainers are reachable (many are in the community, or at least active on GitHub/social)
- battle tested (this doesn't always mean you need a 1.0 fwiw, or an older/established package. often we do the testing in the community for newer packages, long before we adopt it)

nano-staged is maintained by someone we know is active and reachable, and also invested in the package (i.e. they are very unlikely to abandon it). it is probably a good thing they haven't published a new version in a while as it shows stability

**Comment by will-stone** [comment]
Thanks for your reply. A strict criteria isn't necessarily required, but maybe the examples you've given could be fineness-ed into something that could live on the README?

As for nano-staged, I see what you mean: the issue lies upstream and the query lies with that project as to why they haven't gone to v1. Looking for something that follows proper SemVer is probably a valid requirement though, seeing as [ZeroVer](https://0ver.org/zerover_0_based_versioning.html) has become a bit of a meme now, and maintainers might not be too keen to accept replacements to non-semver-following packages.

If you are happy to write down some entrance criteria (even loosely), I'd also propose writing some exit criteria: e.g. `lint-staged` might adopt a lot of e18e proposals and once again become a more viable option over nano-staged.

Anyway, thanks again 🙂
