### ISSUE TITLE
prop-types

### ISSUE THREAD

**Issue by benmccann** [es-tooling/module-replacements#31]
See https://stackoverflow.com/questions/73954484/should-i-use-the-package-prop-types-or-pass-a-props-interface-to-react-component

Should it be applied conditionally only to Typescript projects though? That might require some new functionality in the plugin

**Comment by 43081j** [comment]
i wonder if it sits better with one of the react specific eslint plugins (e.g. one of the alternatives to eslint-plugin-react we probably list here)

since the rule could then be "if in typescript, assert that an interface is used, otherwise, assert prop-types is used" etc

**Comment by benmccann** [comment]
Filed issues there to see what the maintainers of those libraries think about the idea:
- https://github.com/shimful/eslint-plugin-react-lite/issues/4
- https://github.com/Rel1cx/eslint-react/issues/597

**Comment by benmccann** [comment]
Closing this since the rule now exists in one of the eslint libraries
