### ISSUE TITLE
eslint-plugin-import alternatives

### ISSUE THREAD

**Issue by 43081j** [es-tooling/module-replacements#4]
we should document alternatives to this lint plugin

following the template here:
https://github.com/es-tooling/module-replacements/blob/main/docs/templates/module.md

example:
https://github.com/es-tooling/module-replacements/blob/main/docs/modules/npm-run-all.md

@JounQin you probably know better than me here, any chance you could start the doc in `docs/modules/eslint-plugin-import.md`?

it'll probably only have one alternative right now: `eslint-plugin-i`, unless you decided to rename in the end

ill get it added to the `depend` lint plugin once its here

**Comment by JounQin** [comment]
It's now https://github.com/un-es/eslint-plugin-import-x

I'll try to raise a PR when I'm free.

**Comment by zloirock** [comment]
[It's here](https://github.com/es-tooling/module-replacements/blob/main/docs/modules/eslint-plugin-import.md), so I think that it can be closed.

**Comment by 43081j** [comment]
good catch! closing 👍
