### ISSUE TITLE
`resolve`

### ISSUE THREAD

**Issue by AbhiPrasad** [es-tooling/module-replacements#58]
We can replace [`resolve`](https://www.npmjs.com/package/resolve) with built-ins starting Node `8.9.0` and above.

It [pulls in a bunch of deps](https://npmgraph.js.org/?q=resolve), and doesn’t support exports field and custom conditions (which is very common in modern JS apps).

<img width="756" alt="image" src="https://github.com/es-tooling/module-replacements/assets/18689448/13dbca16-0379-4aa7-be50-d670ae19215a">

For CJS you can use `require.resolve`. ESM is more tricky, you prob need https://www.npmjs.com/package/resolve.exports, but there is [`import.meta.resolve`](https://nodejs.org/api/esm.html#importmetaresolvespecifier) that was introduced with Node `20.6.0`

~Here's an example PR I opened up with rollup that does the ESM thing~: https://github.com/rollup/plugins/pull/1742 (I may have to change this to make it work with ESM, need more testing)

Here's an example PR (that tbh should be merged in to `require-in-the-middle`) that does the CJS port: https://github.com/elastic/require-in-the-middle/pull/25

**Comment by AbhiPrasad** [comment]
From @antfu on [discord](https://discord.com/channels/1227627367204257852/1227653370945474590/1256413814132314122):

> Resolve is a very complex problem to solve. `require.resolve` only resolve CJS conditions. For ESM and custom conditions, you might want https://www.npmjs.com/package/resolve.exports, but that still, wouldn't even be closer to a 1:1 replacement of resolve.

**Comment by AbhiPrasad** [comment]
https://packages.ecosyste.ms/registries/npmjs.org/packages/resolve/dependent_packages?kind=runtime&order=desc&sort=downloads

**Comment by benmccann** [comment]
I don't think we can just suggest this one to be replaced. Sometimes you can, but very often projects are using APIs from `resolve` that are not available in `require.resolve`

**Comment by ljharb** [comment]
fwiw you can replace `supports-preserve-symlinks-flag` with `export default typeof window === 'undefined' ? true : null;` if it's node 6.2+ (and if you have separate node and browser files, one is just `true` and the other just `null`.

I think `is-core-module` you're already replacing, and `path-parse` can be replaced with `export { parse } from 'path'` in node >= 0.12.

Sadly `import.meta.resolve` is both flagged and broken in all sorts of ways, so it's likely not yet a viable option.

**Comment by AbhiPrasad** [comment]
> Sadly `import.meta.resolve` is both flagged and broken in all sorts of ways, so it's likely not yet a viable option.

Yes, unfortunately it's nowhere near robust enough (also one of the many reasons why I believe ESM is not prime-time yet, but that's another debate).

We probably need to push for a proposal like https://github.com/nodejs/node/issues/51855, which would also help with many of the hacks that https://github.com/nodejs/import-in-the-middle and https://github.com/vercel/nft/ have to do.

thanks for the advice @ljharb!

> I don't think we can just suggest this one to be replaced. Sometimes you can, but very often projects are using APIs from resolve that are not available in require.resolve

This feels reasonable, I'll close this then! And see if I can get anyone excited about helping expose some stuff in Node.js directly 😄.
