### ISSUE TITLE
`sort-object`

### ISSUE THREAD

**Issue by AbhiPrasad** [es-tooling/module-replacements#59]
https://www.npmjs.com/package/sort-object brings in a ton of deps:

<img width="1056" alt="image" src="https://github.com/es-tooling/module-replacements/assets/18689448/2c2f8a8b-629d-4d43-9e14-6c362da83242">

https://npmgraph.js.org/?q=sort-object

https://pkg-size.dev/sort-object - 166KB / 19 packages

Replacement:

```ts
const sortObj = require('sort-object');

const object = {a: 1, c: 2, b: 3};

// old
sortObj(object);

// new
Object.keys(object).sort().reduce(
  (obj, key) => { 
    obj[key] = object[key]; 
    return obj;
  }, 
  {}
);
```

**Comment by 43081j** [comment]
this could be a good one for an alternative package if one doesn't exist yet

the boilerplate of having to write that code every time will be a pain. so good opportunity for some kind of tiny version of the same functionality

worth having a look around for some alternatives first 👍

**Comment by 43081j** [comment]
@keithamus from chai seems to have one!

https://www.npmjs.com/package/sort-object-keys

maybe we can add this as a replacement
