### ISSUE TITLE
incorporate horcrux list

### ISSUE THREAD

**Issue by benmccann** [es-tooling/module-replacements#65]
A great list of packages here: https://www.npmjs.com/package/all-the-horcrux

**Comment by AbhiPrasad** [comment]
Although I understand the frustration, I hope this initiative avoids the language/messaging displayed in that package. Even referring to some of the packages as `horcrux` feels off. I know we are trying to cut the bloated nature of the ecosystem, but we shouldn't throw the baby out with the bathwater. There are definitely some packages in the list that are still valuable to the ecosystem at large.

On that same vein, I don't think calling anyone "Dark Lord" (or deatheaters) is productive - especially when the person referenced by this package is coming and helping us think about replacements and their tradeoffs! See: https://github.com/es-tooling/module-replacements/issues/58#issuecomment-2197869098 as an example. We should be trying to make more of these interactions happen, and I fear this kind of talk just puts that in danger.

There should be room for everyone here, that's part of the reason why I also want to help out.

**Comment by 43081j** [comment]
i would say the same

its a useful list if you want to find these packages in particular, but the wording is off.

some consumers need to support much older node runtimes, and so much of this project doesn't apply to them. though it wouldn't be fair to paint those people as being terrible etc, they just have different requirements to us. we can be happy we have the flexibility to target higher node versions than they can.

im going to close this one, but if anyone wants to use the list as reference to create some additions to this repo, go for it

**Comment by benmccann** [comment]
yes, I agree 100% that the wording shouldn't be incorporated here and there's no need to make anything personal. The interesting thing to me was that someone had compiled such a long list of packages where the vast majority are replaced by native browser APIs
