### ISSUE TITLE
`eslint-plugin-n` instead of `eslint-plugin-node`

### ISSUE THREAD

**Issue by Lehoczky** [es-tooling/module-replacements#9]
eslint-plugin-node is no longer maintained and has been forked as eslint-plugin-n.

Their repositories: 
- https://github.com/mysticatea/eslint-plugin-node
- https://github.com/eslint-community/eslint-plugin-n

**Comment by 43081j** [comment]
would be good to add that to the docs here:
https://github.com/es-tooling/module-replacements/tree/main/docs/modules

and then we can pull it into eslint-plugin-depend too

**Comment by Lehoczky** [comment]
No worries, I will do it tomorrow ;)
