### ISSUE TITLE
`traverse` -> `neotraverse`

### ISSUE THREAD

**Issue by PuruVJ** [es-tooling/module-replacements#98]
Recently made this https://x.com/puruvjdev/status/1811382220038234296. 100% drop-in replacement(in terms of API, neotraverse/legacy for older browsers & CJS support)

I'd love to make a PR, just not sure the format and which all files to touch. Would be nice to have a CONTRIBUTING.md explaining this 😄

**Comment by 43081j** [comment]
You can add a new doc following this template: 
https://github.com/es-tooling/module-replacements/blob/main/docs/templates/module.md

If you know of any other alternatives too, it would be worth listing those so people have options. No worries if you're not aware of any though
